services:
  - type: web
    name: snowcast
    env: node
    plan: starter
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_SESSION_SECRET
        sync: false
      - key: BACKEND_SESSION_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_API_ENDPOINT_URL
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: CLIENT_API_SESSION_SECRET
        sync: false
      - key: CORS_FRONTEND_ORIGINS
        sync: false
      - key: EMAIL_IMAGE_BASE_URL
        sync: false
      - key: EMAIL_EMBED_IMAGES
        value: "false"
      - key: BACKEND_ADMIN_ENABLED
        value: "false"
